aliases:
  - &node
    - image: circleci/node:9

  - &checkout-submodules
      name: Checkout submodules
      command: git submodule update --init --recursive

  - &save-repo-cache
      key: repo-cache-{{ .Environment.CIRCLE_SHA1 }}
      paths:
        - ~/project

  - &restore-repo-cache
      key: repo-cache-{{ .Environment.CIRCLE_SHA1 }}

  - &save-dependencies-cache
      key: dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      paths:
        - ./node_modules
        - ./jspm_packages

  - &restore-dependencies-cache
      keys:
        - dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
        # fallback in case checksum fails
        - dependencies-{{ .Branch }}

  - &save-build-cache
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./build

  - &restore-build-cache
      key: build-cache-{{ .Environment.CIRCLE_SHA1 }}

  - &install-npm
      name: Install latest version of npm
      command: sudo npm install -g npm@latest

  - &deploy
      name: Deploy if tests pass and branch is master
      command: |
        ssh-keyscan $SERVER_IP > ~/.ssh/known_hosts
        cat dockerfile.template | envsubst > dockerfile
        tar cvzf app.tgz dockerfile build/
        scp app.tgz core@$SERVER_IP:~/kotsutgz
        scp deploy.sh core@$SERVER_IP:~/deploy.sh
        ssh core@$SERVER_IP chmod +x deploy.sh
        ssh core@$SERVER_IP ./deploy.sh $CIRCLE_PROJECT_REPONAME $CIRCLE_SHA1

version: 2
jobs:
  checkout:
    machine: true
    steps:
      - checkout
      - run: *checkout-submodules
      - save_cache: *save-repo-cache

  setup:
    docker: *node
    steps:
      - run: *install-npm
      - restore_cache: *restore-repo-cache
      - restore_cache: *restore-dependencies-cache
      - run: npm install
      - save_cache: *save-dependencies-cache

  test:
    docker: *node
    steps:
      - restore_cache: *restore-repo-cache
      - restore_cache: *restore-dependencies-cache
      - run: npm run test

  build:
    docker: *node
    steps:
      - restore_cache: *restore-repo-cache
      - restore_cache: *restore-dependencies-cache
      - run: npm run build
      - save_cache: *save-build-cache

  greenkeeper:
    docker: *node
    steps:
      - restore_cache: *restore-repo-cache
      - run: sudo npm install -g greenkeeper-lockfile@latest
      - run: |
          greenkeeper-lockfile-update
          greenkeeper-lockfile-upload

  deploy:
    machine: true
    steps:
      - restore_cache: *restore-repo-cache
      - restore_cache: *restore-build-cache
      - deploy: *deploy

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - checkout
      - setup:
          requires:
            - checkout
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
      - greenkeeper:
          requires:
            - test
            - build
          filters:
            branches:
              only: /^greenkeeper.*/
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
